### ISSUE TITLE
AddressSanitizer: attempting double-free

### ISSUE THREAD

**Issue by tianmai1** [michaelrsweet/codedoc#16]
./codedoc poc188
version 3.7
```
==102826==ERROR: AddressSanitizer: attempting double-free on 0x6080000014a0 in thread T0:
    #0 0x7f8e1b7577a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x5567506d6cae in scan_file /home/tianmai/workspace/codedoc(复件)/codedoc.c:3668
    #2 0x5567506ccb8e in main /home/tianmai/workspace/codedoc(复件)/codedoc.c:531
    #3 0x7f8e1ae7fc86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
    #4 0x5567506cb5e9 in _start (/home/tianmai/workspace/codedoc(复件)/codedoc+0xe5e9)

0x6080000014a0 is located 0 bytes inside of 88-byte region [0x6080000014a0,0x6080000014f8)
freed by thread T0 here:
    #0 0x7f8e1b7577a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x7f8e1b4739e2 in mxmlDelete /home/tianmai/mxml-3.2/mxml-node.c:231

previously allocated by thread T0 here:
    #0 0x7f8e1b757d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x7f8e1b473664 in mxml_new /home/tianmai/mxml-3.2/mxml-node.c:841

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8) in __interceptor_free
==102826==ABORTING
```
[poc188.zip](https://github.com/michaelrsweet/codedoc/files/12034267/poc188.zip)

**Comment by michaelrsweet** [comment]
[master 80fc3ce] Fix double-free bug (Issue #16)
